force-app/main/default/objects/Document__c/fields/Extensions__c.field-meta.xml
<CustomField>
    <fullName>Extensions__c</fullName>
    <label>Extensions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>.docx</fullName>
            </value>
            <value>
                <fullName>.pdf</fullName>
            </value>
            <value>
                <fullName>.ppt</fullName>
            </value>
            <value>
                <fullName>.pptx</fullName>
            </value>
            <value>
                <fullName>.xls</fullName>
            </value>
            <value>
                <fullName>.xlsx</fullName>
            </value>
            <value>
                <fullName>.gif</fullName>
            </value>
            <value>
                <fullName>.jpg</fullName>
            </value>
            <value>
                <fullName>.png</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Multiple__c.field-meta.xml
<CustomField>
    <fullName>Multiple__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Multiple</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>Enter API name for the object</inlineHelpText>
    <label>Object</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IndividualDoc__c/IndividualDoc__c.object-meta.xml
<CustomObject>
    <label>IndividualDoc</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>IndividualDoc Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IndividualDocs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IndividualDoc__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <referenceTo>Document__c</referenceTo>
    <relationshipLabel>IndividualDocs</relationshipLabel>
    <relationshipName>Document</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/FileUploadAllTest.cls
@istest
public class FileUploadAllTest {
    @testsetup
    public static void createdata()
    {
        Account test=new account();
        test.Name='Vikas';
        insert test;
        Document__c doc= new Document__c();
        doc.Active__c=true;
        doc.Extensions__c='.pdf';
        doc.Multiple__c=true;
        doc.Object__c='Account';
        doc.Name='Adhaar';
        insert doc;
    }
    @istest
    private static void testgetfiles()
    {
        Account acc= [select id from account];
        FileUploadAll.getAllFiles(acc.Id,'Account');
        
    }
    @istest
    private static void testgetfiles2()
    {
        Document__c doc= [select id from Document__c];
        IndividualDoc__c ind=new IndividualDoc__c();
        
        Account acc= [select id from account];
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion;    
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        ind.ParentId__c=acc.id;
        ind.Document__c=doc.id;
        insert ind;
        //create ContentDocumentLink  record 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = ind.id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;
        
        FileUploadAll.getAllFiles(acc.Id,'Account');
        
    }
    
    
}