force-app/main/default/objects/Document__c/fields/Extensions__c.field-meta.xml
<CustomField>
    <fullName>Extensions__c</fullName>
    <label>Extensions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>.docx</fullName>
            </value>
            <value>
                <fullName>.pdf</fullName>
            </value>
            <value>
                <fullName>.ppt</fullName>
            </value>
            <value>
                <fullName>.pptx</fullName>
            </value>
            <value>
                <fullName>.xls</fullName>
            </value>
            <value>
                <fullName>.xlsx</fullName>
            </value>
            <value>
                <fullName>.gif</fullName>
            </value>
            <value>
                <fullName>.jpg</fullName>
            </value>
            <value>
                <fullName>.png</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Multiple__c.field-meta.xml
<CustomField>
    <fullName>Multiple__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Multiple</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>Enter API name for the object</inlineHelpText>
    <label>Object</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Single__c.field-meta.xml
<CustomField>
    <fullName>Single__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Single</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IndividualDoc__c/IndividualDoc__c.object-meta.xml
<CustomObject>
    <label>IndividualDoc</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>IndividualDoc Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IndividualDocs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IndividualDoc__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <referenceTo>Document__c</referenceTo>
    <relationshipLabel>IndividualDocs</relationshipLabel>
    <relationshipName>Document</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/FileUploadAll.cls
public with sharing class FileUploadAll {
    public FileUploadAll() {

    }
    class data{
        @auraenabled public  IndividualDoc__c docs;
@auraenabled public Integer size=0;
@auraenabled public list<ContentDocumentLink> attachments;
@auraenabled public list<ContentVersion> contentversions;


    }
    @AuraEnabled
    public static  list<data>  getAllFiles(string recordid,string objectName){
        list<data> datas= new list<data>();
        system.debug(recordid+' '+objectName);
    list<Document__c> docs=[SELECT id,name,Single__c,Object__c,Multiple__c,Extensions__c,Active__c FROM Document__c where Object__c=:objectName and Active__c=true];     
    list<IndividualDoc__c> attachs=new list<IndividualDoc__c>();
    Map<id,list<ContentDocumentLink>> parentvslink= new Map<id,list<ContentDocumentLink>>();
    Map<id,list<ContentVersion>> parentvsversion= new Map<id,list<ContentVersion>>();
    Map<id,list<ContentVersion>> recvsversion= new Map<id,list<ContentVersion>>();
                
    list<IndividualDoc__c> finalList=new list<IndividualDoc__c>();
            if(docs.size()>0)
            {
                list<IndividualDoc__c> attached=[SELECT id,Name,ParentId__c,Document__c	,Document__r.name,Document__r.Single__c,Document__r.Object__c,Document__r.Multiple__c,Document__r.Extensions__c,Document__r.Active__c from IndividualDoc__c where Document__c in :docs and ParentId__c=:recordid];
                if(attached.size()<1)
                {
                    for(Document__c doc:docs)
                    {
                        IndividualDoc__c attachm= new IndividualDoc__c();
                        attachm.Document__c= doc.id;
                        attachm.ParentId__c=recordid;
                        attachs.add(attachm);

                    }
                    if(attachs.size()>0)
                    {
                        insert attachs;
                        finalList=[SELECT id,Name,ParentId__c,Document__c	,Document__r.name,Document__r.Single__c,Document__r.Object__c,Document__r.Multiple__c,Document__r.Extensions__c,Document__r.Active__c from IndividualDoc__c where id in :attachs];
                
                        
                    }
                }
                else {
                    finalList=attached;
                    list<id> linked= new list<id>();
                    for(IndividualDoc__c att:attached)
                    {
                        linked.add(att.id);
                    }
                    
                    list<ContentDocumentLink> links= [Select id,linkedentityid,ContentDocument.contentsize,ContentDocument.FileType,ContentDocumentId,ContentDocument.title, ContentDocument.LatestPublishedVersionId from ContentDocumentLink where linkedentityid  in:linked];
                set<id> docid= new set<id>();
                
                  
                    for(ContentDocumentLink link:links)
                    {
                        docid.add(link.contentdocumentid);
                        if(parentvslink.containsKey(link.linkedentityid))
                        {
                            list<ContentDocumentLink> ln=parentvslink.get(link.linkedentityid);
                            
                             ln.add(link);
                                parentvslink.put(link.linkedentityid,ln);

                            

                        }
                        else {
                            list<ContentDocumentLink> ln= new list<ContentDocumentLink>();
                            ln.add(link);
                            parentvslink.put(link.linkedentityid,ln);

                        }
                    }
                   /* List<ContentVersion> conversions=[SELECT Id, ContentDocumentId, ContentUrl, VersionNumber, ContentBodyId, Title, Description, PathOnClient, ContentModifiedDate, FileType, ContentSize FROM ContentVersion where ContentDocumentId in :docid];

                    
                    for(ContentVersion conversion:conversions)
                    {
                       
                        if(parentvsversion.containsKey(conversion.ContentDocumentId))
                        {
                            list<ContentVersion> ln=parentvsversion.get(conversion.ContentDocumentId);
                            
                             ln.add(conversion);
                             parentvsversion.put(conversion.ContentDocumentId,ln);

                            

                        }
                        else {
                            list<ContentVersion> ln= new list<ContentVersion>();
                            ln.add(conversion);
                            parentvsversion.put(conversion.ContentDocumentId,ln);

                        }
                    }
                    for(ContentDocumentLink link:links)
                    {
                        recvsversion.put(link.linkedentityid,parentvsversion.get(link.ContentDocumentId));

                    }   */
             
                }
               
                for(IndividualDoc__c indi:finalList)
                {
                    data d= new data();
                    d.docs= indi;
                   // d.size=parentvslink.get(indi.id).size();
                    d.attachments=parentvslink.get(indi.id);
                   // d.contentversions=recvsversion.get(indi.id);
                    datas.add(d);
                }
              
                
            }
            return datas;
                
       
    }
}